; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

; Let PlatformIO auto-detect the port again
monitor_speed = 115200

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -I include

board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi

board_build.flash_size = 8MB

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    file://lib/edgeimpulse



 ; monitor_port = /dev/ttyACM*

; Force the terminal to tell the ESP32 it is ready to receive data
monitor_dtr = 1
monitor_rts = 1
monitor_echo = yes
monitor_filters = send_on_enter
lib_ldf_mode = deep+