#pragma once

#define WIFI_SSID "COLOQUE_A_REDE_AQUI"
#define WIFI_PASSWORD "COLOQUE_A_SENHA_AQUI"

#define GEMINI_API_KEY "COLOQUE_A_CHAVE_AQUI"
#define AZURE_SPEECH_KEY "COLOQUE_A_CHAVE_AQUI"
#define AZURE_SPEECH_REGION "COLOQUE_A_REGIAO_AQUI"